language: node_js

os:
  - linux
  - osx
  - windows

matrix:
  allow_failures:
    - os: windows

node_js:
  - '7'
  - '8'
  - '9'
  - 'lts/*'
  - 'node'

install:
  - npm install

script:
  - npm run build
