---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: index.njk
  label: Index
- type: document
  path: about.njk
  label: About me
- type: document
  path: software.njk
  label: Software
  match: "**/*"
- type: document
  path: writing.njk
  label: Writing
  match: "**/*"
- type: document
  path: photography.njk
  label: Photography
  match: "**/*"
- type: document
  path: contact.njk
  label: Contact
upload_dir: assets/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: _site
  install_dependencies_command: npm install
  preview_docker_image: node:14
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
